### ISSUE TITLE
Cannot find module 'Main'

### ISSUE THREAD

**Issue by Matthew1172** [newlandsvalley/purescript-abc-parser#41]
How do you run the parser? When I do:
```pulp run```
I get
```
* Building project in C:\...\...\...\purescript-abc-parser
* Build successful.
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'Main'
Require stack:
- C:\...\...\AppData\Local\Temp\pulp-run2022222-14824-131d0pd.49pxi.js\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (C:\...\...\AppData\Local\Temp\pulp-run2022222-14824-131d0pd.49pxi.js\index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\...\\...\\AppData\\Local\\Temp\\pulp-run2022222-14824-131d0pd.49pxi.js\\index.js'
  ]
}
* ERROR: Subcommand terminated with exit code 1
```
It would be nice if someone beefed up the readme with instructions on how to parse an ```.abc``` file.

**Comment by newlandsvalley** [comment]
It's a library, not an executable.  You need to write your own module with your own main, link with the library and call the parser.  Perhaps look at the tests - they have a main.  Look at the Abc tests in particular.

Also - are you familiar with Pursuit?  For example: https://pursuit.purescript.org/packages/purescript-abc-parser/1.8.0/docs/Data.Abc.Parser should help.
